<a href="https://colab.research.google.com/github/arny617/MLNanodegree/blob/master/Crypto_SentimentAnalysis_RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
import gensim
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
from nltk.corpus import stopwords as sw
from nltk.tokenize import word_tokenize
from nltk import pos_tag
import numpy as np
import nltk
import os
nltk.download('wordnet')
import pandas as pd
import numpy as np
import pickle
import joblib

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [3]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


True

In [ ]:
!pip install pysentiment

     |████████████████████████████████| 2.8MB 12.6MB/s 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


In [4]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from textblob import TextBlob
import gensim

/usr/local/lib/python3.6/dist-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [5]:
!pip install OpenBlender

     |████████████████████████████████| 61kB 5.6MB/s 
     |████████████████████████████████| 245kB 19.3MB/s 
  Created wheel for OpenBlender: filename=OpenBlender-2.6-cp36-none-any.whl size=6607 sha256=09fbeaba11c41b8b085d6ae177b6c7e592e54beef3cd5346ad4ad61e9b98d3c5
  Stored in directory: /root/.cache/pip/wheels/fd/29/7b/377afef16a792ed174a9ade5a6707ef87843e214476d0c8205
Successfully built OpenBlender


In [6]:
import OpenBlender

In [7]:
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
import matplotlib.pyplot as plt

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
import os
from google.colab import drive
drive.mount('/content/gdrive')
ROOT = "/content/gdrive/My Drive/Colab Notebooks/NLP/Fast.ai_IntroToNLP/"
os.chdir(ROOT)

Mounted at /content/gdrive


In [ ]:
api_token = '5fc5ad47951629617230bee5MDHzrVvlWhz1MZm92QeQqc5DrybPBT'

In [ ]:
action = 'API_getObservationsFromDataset'# ANCHOR: 'Bitcoin vs USD'
  
parameters = { 
    'token' : api_token,
    'id_dataset' : '5d4c3af79516290b01c83f51',
    'date_filter':{"start_date" : "2020-01-01",
                   "end_date" : "2020-08-29"} }
df = pd.read_json(json.dumps(OpenBlender.call(action, parameters)['sample']), convert_dates=False, convert_axes=False).sort_values('timestamp', ascending=False)
df.reset_index(drop=True, inplace=True)
df['date'] = [OpenBlender.unixToDate(ts, timezone = 'GMT') for ts in df.timestamp]
df = df.drop('timestamp', axis = 1)

Task ID: '5fc84fb90895fafb4a9d8d4b'.
Total estimated consumption: 5832.61 processing units.
Task confirmed. Starting download..
100.0 % completed.


In [ ]:
df['log_ret'] = np.log(df['price']) - np.log(df['open'])

In [ ]:
df['target'] = [1 if log_diff > 0 else 0 for log_diff in df['log_ret']]

In [ ]:
format = '%d-%m-%Y %H:%M:%S'
timezone = 'GMT'
df['u_timestamp'] = OpenBlender.dateToUnix(df['date'], 
                                           date_format = format, 
                                           timezone = timezone)
df = df[['date', 'u_timestamp', 'price', 'target']]
df.head()

date   u_timestamp    price  target
0  28-08-2020 17:00:00  1.598634e+09  11545.0       1
1  27-08-2020 17:00:00  1.598548e+09  11343.0       0
2  26-08-2020 17:00:00  1.598461e+09  11471.0       1
3  25-08-2020 17:00:00  1.598375e+09  11341.0       0
4  23-08-2020 17:00:00  1.598202e+09  11663.0       0

In [ ]:
blend_source = {
                'id_dataset':'5ea2039095162936337156c9',
                'feature' : 'text'
            }
# Now, let's 'timeBlend' it to our dataset
df_blend = OpenBlender.timeBlend( token = api_token,
                                  anchor_ts = df.u_timestamp,
                                  blend_source = blend_source,
                                  blend_type = 'agg_in_intervals',
                                  interval_size = 60 * 60 * 24,
                                  direction = 'time_prior',
                                  interval_output = 'list',
                                  missing_values = 'raw')
df = pd.concat([df, df_blend.loc[:, df_blend.columns != 'u_timestamp']], axis = 1)
df.head()

Task ID: '5fc850470895fafb4a9d8d4c'.
Total estimated consumption: 9440.0 processing units.
Task confirmed. Starting download..
100%


date  ...                          BITCOIN_NE.text_last1days
0  28-08-2020 17:00:00  ...  [etoro ceo yoni assia on reaching 12 million u...
1  27-08-2020 17:00:00  ...  [government confirms crypto profits not taxabl...
2  26-08-2020 17:00:00  ...  [ticker tool uses the bch blockchain to provid...
3  25-08-2020 17:00:00  ...  [crypto fundraising is changing again in 2020 ...
4  23-08-2020 17:00:00  ...  [subhash chandra garg on the future of crypto ...

[5 rows x 7 columns]

In [ ]:
df['text'] = df['BITCOIN_NE.text_last1days'].apply(lambda x:"xxeos ".join(x))

In [ ]:
vader_analyzer = SentimentIntensityAnalyzer()

In [ ]:
df["text_polarity"] = df["text"].apply(lambda x : vader_analyzer.polarity_scores(x))
df["text_subjectivity"] = df["text"].apply(lambda x : TextBlob(x).sentiment[1])

In [ ]:
# BTC Text Vectorizer
blend_source = { 
                'id_textVectorizer':'5f739fe7951629649472e167'
               }
df_blend = OpenBlender.timeBlend( token = api_token,
                                  anchor_ts = df.u_timestamp,
                                  blend_source = blend_source,
                                  blend_type = 'agg_in_intervals',
                                  interval_size = 60 * 60 * 24,
                                  direction = 'time_prior',
                                  interval_output = 'list',
                                  missing_values = 'raw').add_prefix('VEC.')

Task ID: '5fc857840895fafb4a9d8d4c'.
Total estimated consumption: 10479.43 processing units.
Task confirmed. Starting download..
100%


In [ ]:
df_anchor = pd.concat([df, df_blend.loc[:, df_blend.columns != 'timestamp']], axis = 1)
df_anchor.head()

date   u_timestamp  ...  VEC.digital gold  VEC.minister
0  28-08-2020 17:00:00  1.598634e+09  ...                 0             0
1  27-08-2020 17:00:00  1.598548e+09  ...                 0             0
2  26-08-2020 17:00:00  1.598461e+09  ...                 0             0
3  25-08-2020 17:00:00  1.598375e+09  ...                 0             0
4  23-08-2020 17:00:00  1.598202e+09  ...                 0             0

[5 rows x 1232 columns]

In [ ]:
df_anchor.to_csv("BTC_Final.csv")

In [ ]:
df_anchor["text_posneg"] = df_anchor["text_polarity"].apply(lambda x : 0 if x["neg"]==0.0 else x["pos"]/x["neg"]) 


In [ ]:
df_anchor["text_polarity"] = df_anchor["text_polarity"].apply(lambda x : x["compound"]) 

In [ ]:
df_final = df_anchor[df_anchor.columns[~df_anchor.columns.isin(['timestamp','price','BITCOIN_NE.text_COUNT_last1days','BITCOIN_NE.text_last1days','text','VEC.source'])]]

In [ ]:
corr_matrix

u_timestamp    target  ...  VEC.minister  text_posneg
u_timestamp           1.000000  0.078198  ...      0.125237     0.167387
target                0.078198  1.000000  ...      0.055801     0.052693
text_polarity         0.129950  0.003190  ...      0.133839     0.583386
text_subjectivity     0.236463  0.007029  ...      0.044016     0.073185
VEC.block reward      0.024866  0.085648  ...      0.012139     0.050108
...                        ...       ...  ...           ...          ...
VEC.expands           0.011814  0.055801  ...      0.017241     0.232921
VEC.integrates        0.012055  0.018256  ...      0.019318     0.323036
VEC.digital gold      0.047789  0.055801  ...      0.017241     0.014563
VEC.minister          0.125237  0.055801  ...      1.000000     0.081881
text_posneg           0.167387  0.052693  ...      0.081881     1.000000

[1226 rows x 1226 columns]

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score# We drop correlated features because with so many binary 
# ngram variables there's a lot of noise

corr_matrix = df_final.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

In [ ]:
df_final.drop([column for column in upper.columns if any(upper[column] > 0.6)], axis=1, inplace=True)
# Now we separate in train/test sets
df_final.head()

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


date   u_timestamp  ...  VEC.digital gold  text_posneg
0  28-08-2020 17:00:00  1.598634e+09  ...                 0     0.000000
1  27-08-2020 17:00:00  1.598548e+09  ...                 0     5.656250
2  26-08-2020 17:00:00  1.598461e+09  ...                 0     0.762295
3  25-08-2020 17:00:00  1.598375e+09  ...                 0     1.428571
4  23-08-2020 17:00:00  1.598202e+09  ...                 0     3.653061

[5 rows x 872 columns]

In [ ]:
df_final

date   u_timestamp  ...  VEC.digital gold  text_posneg
0    28-08-2020 17:00:00  1.598634e+09  ...                 0     0.000000
1    27-08-2020 17:00:00  1.598548e+09  ...                 0     5.656250
2    26-08-2020 17:00:00  1.598461e+09  ...                 0     0.762295
3    25-08-2020 17:00:00  1.598375e+09  ...                 0     1.428571
4    23-08-2020 17:00:00  1.598202e+09  ...                 0     3.653061
..                   ...           ...  ...               ...          ...
231  05-01-2020 17:00:00  1.578244e+09  ...                 0     0.000000
232  04-01-2020 17:00:00  1.578157e+09  ...                 0     0.000000
233  03-01-2020 17:00:00  1.578071e+09  ...                 0     0.000000
234  02-01-2020 17:00:00  1.577984e+09  ...                 0     0.000000
235  01-01-2020 17:00:00  1.577898e+09  ...                 0     0.000000

[236 rows x 872 columns]

In [ ]:
X = df_final.iloc[:,3:].values
y = df_final.iloc[:,2].values

In [ ]:
div = int(round(len(X) * 0.2))
X_train = X[:div]
y_train = y[:div]
X_test = X[div:]
y_test = y[div:]
# Finally, we perform ML and see results

In [ ]:
X_train[:10]

array([[ 0.2023    ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.9136    ,  0.4625    ,  0.        , ...,  0.        ,
         0.        ,  5.65625   ],
       [-0.5647    ,  0.25416667,  0.        , ...,  0.        ,
         0.        ,  0.76229508],
       ...,
       [ 0.4588    ,  0.05      ,  0.        , ...,  0.        ,
         1.        ,  2.33333333],
       [ 0.2691    ,  0.48166667,  0.        , ...,  0.        ,
         0.        ,  1.28358209],
       [-0.7351    ,  0.70666667,  0.        , ...,  0.        ,
         0.        ,  0.47619048]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import metrics
forest = RandomForestClassifier(random_state = 0)

In [ ]:
rf = RandomForestRegressor(n_estimators = 1000, random_state=0)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
df_res = pd.DataFrame({'y_test':y_test, 'y_pred':y_pred})

In [ ]:
threshold = 0.5
preds = [1 if val > threshold else 0 for val in df_res['y_pred']]
print(metrics.confusion_matrix(preds, df_res['y_test']))
print('Accuracy Score:')
print(accuracy_score(preds, df_res['y_test']))
print('Precision Score:')
print(precision_score(preds, df_res['y_test']))

[[19 19]
 [73 78]]
Accuracy Score:
0.5132275132275133
Precision Score:
0.8041237113402062


In [ ]:
n_estimators = [200, 500, 1000]
max_depth = [5, 15, 25, 30]
min_samples_split = [2, 5, 10,]
min_samples_leaf = [1, 2, 5, 10] 

hyperF = dict(n_estimators = n_estimators, max_depth = max_depth,  
              min_samples_split = min_samples_split, 
             min_samples_leaf = min_samples_leaf)

gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, 
                      n_jobs = -1)
bestF = gridF.fit(X_train, y_train)

Fitting 3 folds for each of 144 candidates, totalling 432 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:   29.6s
[Parallel(n_jobs=-1)]: Done 196 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 432 out of 432 | elapsed:  4.5min finished


In [ ]:
bestF.best_params_

{'max_depth': 5,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 200}

In [ ]:
forest_opt = RandomForestClassifier(max_depth=5,min_samples_leaf=1,min_samples_split=2,n_estimators=200,random_state = 0)

In [ ]:
forest_opt.fit(X_train, y_train)
y_pred_opt = forest_opt.predict(X_test)
df_res_opt = pd.DataFrame({'y_test':y_test, 'y_pred_opt':y_pred_opt})

In [ ]:
print(metrics.confusion_matrix(df_res_opt['y_pred_opt'], df_res_opt['y_test']))
print('Accuracy Score:')
print(accuracy_score(df_res_opt['y_pred_opt'], df_res_opt['y_test']))
print('Precision Score:')
print(precision_score(df_res_opt['y_pred_opt'], df_res_opt['y_test']))

[[ 1  0]
 [91 97]]
Accuracy Score:
0.5185185185185185
Precision Score:
1.0
